
backend:
  name: git-gateway
  branch: main
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
locale: "he"
collections:
  - name: "products"
    label: "מוצרים"
    files:
      - name: "all"
        label: "כל המוצרים"
        file: "content/products.json"
        format: "json"
        fields:
          - label: "מוצרים"
            name: "items"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number"}
              - {label: "שם", name: "name", widget: "string"}
              - {label: "מחיר", name: "price", widget: "number"}
              - {label: "קטגוריה", name: "category", widget: "string"}
              - {label: "תיאור", name: "description", widget: "text"}
              - {label: "תמונה", name: "image", widget: "image"}
  - name: "settings"
    label: "הגדרות אתר"
    files:
      - name: "site"
        label: "הגדרות תשלום"
        file: "config/site.json"
        format: "json"
        fields:
          - {label: "PayPal Client ID", name: "paypal_client_id", widget: "string", required: false}
